// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCN4CWf7JtpxDWB9rwoOGJxmdNHfng2g8',
    appId: '1:725160868831:web:6f4761294d133740a5a26a',
    messagingSenderId: '725160868831',
    projectId: 'interneepk-92',
    authDomain: 'interneepk-92.firebaseapp.com',
    storageBucket: 'interneepk-92.appspot.com',
    measurementId: 'G-NNSLPDHF99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVfQf74LdWU8Oj9xO-jgAgKMajSnOWGXQ',
    appId: '1:725160868831:android:2f37db0313f1a0e2a5a26a',
    messagingSenderId: '725160868831',
    projectId: 'interneepk-92',
    storageBucket: 'interneepk-92.appspot.com',
  );
}
